DAO
AlenaShvedava/SolvdLab pull request #1
Opened 2023-01-30 11:32 UTC by AlenaShvedava

DAO

2023-02-01 23:24 UTC, vboltrukanis requested changes

2023-02-01 23:24 UTC, vboltrukanis commented on ConcertHall/src/main/java/pl/solvd/concerthall/Main.java
> +
clean it

2023-02-01 23:24 UTC, vboltrukanis commented on ConcertHall/src/main/java/pl/solvd/concerthall/dao/impl/AuthorTypesDAOImpl.java
> +    Connection c;
you can make it private.

2023-02-01 23:24 UTC, vboltrukanis commented on ConcertHall/src/main/java/pl/solvd/concerthall/dao/impl/AuthorTypesDAOImpl.java
> +        return authorsList;
```suggestion
        c = ConnectionPool.getInstance().getConnection();
        try {
            List<AuthorTypes> authorsList = getAllAuthorTypes();
            authorsList = authorsList.stream().filter(predicate).collect(Collectors.toList());
        } catch (SQLException e) {
            c.close();
            System.out.println(e.getMessage());
        }
        return authorsList;
```

2023-02-01 23:24 UTC, vboltrukanis commented on ConcertHall/src/main/java/pl/solvd/concerthall/dao/impl/AuthorTypesDAOImpl.java
> +        finally {
```suggestion
        } finally {
```

2023-02-01 23:24 UTC, vboltrukanis commented on ConcertHall/src/main/java/pl/solvd/concerthall/dao/impl/AuthorTypesDAOImpl.java
> +            try {
you can remove try-catch block here, since you are already passing an exception from this function.

2023-02-01 23:24 UTC, vboltrukanis commented on ConcertHall/src/main/java/pl/solvd/concerthall/dao/impl/AuthorsDAOImpl.java
> +                ConnectionPool.close();
tabulation is failed

2023-02-01 23:24 UTC, vboltrukanis commented on ConcertHall/src/main/java/pl/solvd/concerthall/dao/impl/AuthorsDAOImpl.java
> +            System.out.println(e.getMessage());
In case of exception, all you do is printing, but you can't prevent your programm from continue working. This is incorrect, you should either change return type to boolean, so false - smth went wrong, true - everything is fine, or work with exceptions.

2023-02-01 23:24 UTC, vboltrukanis commented on ConcertHall/src/main/java/pl/solvd/concerthall/exceptions/DAOException.java
> +    public DAOException (String message, Throwable cause){
no difference betwee DAOException, ServiceException or just Exception - fix this.

2023-02-01 23:24 UTC, vboltrukanis commented on ConcertHall/src/main/java/pl/solvd/concerthall/models/Authors.java
> +public class Authors {
do you still need this?

2023-02-01 23:24 UTC, vboltrukanis commented on ConcertHall/src/main/java/pl/solvd/concerthall/services/AuthorTypesService.java
> +public interface AuthorTypesService {
add smth here

2023-02-01 23:24 UTC, vboltrukanis commented on ConcertHall/src/main/java/pl/solvd/concerthall/services/impl/AuthorsServiceImpl.java
> +public class AuthorsServiceImpl extends MySqlDAO implements AuthorsService {
Are you planning to implement services in next pr?

2023-02-01 23:24 UTC, vboltrukanis commented on ConcertHall/src/main/resources/mysqlcreds.properties
> +password = devintern
do not expose credentials in guthub!

2023-02-01 23:24 UTC, vboltrukanis commented on ConcertHall/src/main/java/pl/solvd/concerthall/utils/ConnectionPool.java
> +            throw new RuntimeException(e);
What is the reason to catch exception and throw exception?

2023-02-02 09:51 UTC, AlenaShvedava commented on ConcertHall/src/main/java/pl/solvd/concerthall/services/impl/AuthorsServiceImpl.java
> +public class AuthorsServiceImpl extends MySqlDAO implements AuthorsService {
yes

2023-02-02 09:54 UTC, AlenaShvedava commented on ConcertHall/src/main/resources/mysqlcreds.properties
> +password = devintern
not send propertyfile? ok

2023-02-02 09:56 UTC, AlenaShvedava commented on ConcertHall/src/main/java/pl/solvd/concerthall/utils/ConnectionPool.java
> +            throw new RuntimeException(e);
these are sketches, a large structure, I don’t have time to write everything down. But I will. I know that exceptions need to be worked on, as well as logs

2023-02-02 09:57 UTC, AlenaShvedava commented on ConcertHall/src/main/java/pl/solvd/concerthall/dao/impl/AuthorsDAOImpl.java
> +                ConnectionPool.close();
ok

2023-02-22 10:53 UTC, vboltrukanis commented on ConcertHall/src/main/resources/mysqlcreds.properties
> +password = devintern
```
driver = com.mysql.jdbc.Driver
url = jdbc:mysql://SolvdLaba/vb_ConcertHall
login = 
password = 
```

2023-03-03 18:11 UTC, closed without merging